dist: xenial
language: python
cache: pip

git:
    submodules: false

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - python2

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install: 
  - python3 -m pip install -r requirements.txt && python3 -m pip install -e .[dev]

before_script: # configure a headless display to test plot generation
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script: make test

after_success:
    - codecov --token f8f2787b-4aa9-4161-8b13-88ddde282d57
    # - coveralls

branches:
  only:
  - master

notifications:
  email: false
